# Generated by Django 2.2.11 on 2020-10-18 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rent_wala.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid number', regex='^\\+?1?\\d{9,14}$')])),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('first_login', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=100000000000000, unique=True)),
                ('title', models.CharField(default='', max_length=1000000000)),
                ('cat', models.CharField(default='', max_length=1000000000000)),
                ('Poster', models.CharField(default='', max_length=1000000000000)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid number', regex='^\\+?1?\\d{9,14}$')])),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(default='', max_length=50)),
                ('profile_pic', models.CharField(blank=True, max_length=1000)),
                ('validated', models.BooleanField(default=False, help_text='If its True user is validated.')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid number', regex='^\\+?1?\\d{9,14}$')])),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0, help_text='number of OTP sent')),
                ('validated', models.BooleanField(default=False, help_text='If its True user is validated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=1000000000000000000000, unique=True)),
                ('title', models.CharField(default='', max_length=1000000000000000)),
                ('desc', models.CharField(default='', max_length=500)),
                ('subcat', models.CharField(default='', max_length=10000)),
                ('cat', models.CharField(default='', max_length=10000000)),
                ('rent_price', models.CharField(blank=True, default='', max_length=10000000, null=True)),
                ('key1', models.CharField(blank=True, default='', max_length=300)),
                ('key2', models.CharField(blank=True, default='', max_length=300)),
                ('key3', models.CharField(blank=True, default='', max_length=300)),
                ('key4', models.CharField(blank=True, default='', max_length=300)),
                ('Poster', models.CharField(blank=True, default='', max_length=10000000)),
                ('Poster2', models.CharField(blank=True, default='', max_length=10000000)),
                ('Poster3', models.CharField(blank=True, default='', max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, upload_to=rent_wala.models.profile_upload)),
                ('aadhar_card', models.FileField(upload_to=rent_wala.models.file_upload_aadhar)),
                ('pan_card', models.FileField(upload_to=rent_wala.models.file_upload_pan)),
                ('address', models.CharField(max_length=2000, null=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=10000000000)),
                ('delivered', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('order_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('days', models.CharField(default=1, max_length=100)),
                ('title', models.CharField(default='', max_length=1000)),
                ('total', models.CharField(default='', max_length=1000000000000000000000, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('handshake', models.BooleanField(default=False)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.MyUser')),
            ],
        ),
    ]
