# Generated by Django 2.2.11 on 2020-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0002_auto_20201018_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='poster',
            field=models.CharField(default='', max_length=100000000000000000000),
        ),
        migrations.AddField(
            model_name='order',
            name='sid',
            field=models.CharField(default='', max_length=100000000000000000000000),
        ),
    ]
