# Generated by Django 2.2.11 on 2020-10-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0003_auto_20201019_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sid',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='trackorder',
            name='rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.Order'),
        ),
    ]
