# Generated by Django 2.2.11 on 2020-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0004_auto_20201019_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default='', max_length=100000000000000000000000),
        ),
    ]
