# Generated by Django 2.2.11 on 2020-10-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0007_auto_20201019_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_left',
            field=models.CharField(default=1, max_length=1000),
        ),
    ]
