# Generated by Django 2.2.11 on 2020-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0009_myuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='a-1', max_length=100000000000000000000000),
        ),
    ]
