# Generated by Django 2.2.11 on 2020-10-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0010_auto_20201020_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('querry', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.MyUser')),
            ],
        ),
    ]
