# Generated by Django 2.2.11 on 2020-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='checkout_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
