# Generated by Django 2.2.11 on 2020-10-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0013_phoneotp_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackOrder',
        ),
    ]
