# Generated by Django 2.2.11 on 2020-10-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0014_delete_trackorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('days', models.CharField(default=1, max_length=100)),
                ('time_left', models.CharField(default=1, max_length=1000)),
                ('title', models.CharField(default='', max_length=1000)),
                ('total', models.CharField(default='', max_length=1000000000000000000000, null=True)),
                ('order_id', models.CharField(default='a-1', max_length=100000000000000000000000)),
                ('product_id', models.CharField(default='', max_length=100000000000000000000000)),
                ('poster', models.CharField(default='', max_length=100000000000000000000)),
                ('validated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('handshake', models.BooleanField(default=False)),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_wala.MyUser')),
            ],
        ),
    ]
