# Generated by Django 2.2.11 on 2020-11-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_wala', '0016_auto_20201025_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='out_for_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_left',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='validated',
        ),
    ]
